import { useTranslation } from "react-i18next";
const useAllItems = () => {
    const { t } = useTranslation();

    return [
        {
            id: 1,
            img: "/IMG/QishImg.jpg",
            text: t("dataWinter.text"),
            fasil: t("fasil.winter"),
            season: "winter",
        },
        {
            id: 2,
            img: "/IMG/QishImg2.jpg",
            text: t("dataWinter.text2"),
            fasil: t("fasil.winter"),
            season: "winter",
        },
        {
            id: 3,
            img: "/IMG/QishImg3.jpg",
            text: t("dataWinter.text3"),
            fasil: t("fasil.winter"),
            season: "winter",
        },
        {
            id: 4,
            img: "/IMG/QishImg4.jpg",
            text: t("dataWinter.text4"),
            fasil: t("fasil.winter"),
            season: "winter",
        },
        {
            id: 5,
            img: "/IMG/QishImg5.jpg",
            text: t("dataWinter.text5"),
            fasil: t("fasil.winter"),
            season: "winter",
        },
        {
            id: 6,
            img: "/IMG/QishImg6.jpg",
            text: t("dataWinter.text6"),
            fasil: t("fasil.winter"),
            season: "winter",
        },
        {
            id: 7,
            img: "/IMG/QishImg7.jpg",
            text: t("dataWinter.text7"),
            fasil: t("fasil.winter"),
            season: "winter",
        },
        {
            id: 8,
            img: "/IMG/QishImg8.jpg",
            text: t("dataWinter.text8"),
            fasil: t("fasil.winter"),
            season: "winter",
        },
        {
            id: 9,
            img: "/IMG/QishImg9.jpg",
            text: t("dataWinter.text9"),
            fasil: t("fasil.winter"),
            season: "winter",
        },
        {
            id: 10,
            img: "/IMG/QishImg10.jpg",
            text: t("dataWinter.text10"),
            fasil: t("fasil.winter"),
            season: "winter",
        },
        {
            id: 11,
            img: "/IMG/KushImg.jpg",
            text: t("dataAutumn.text"),
            fasil: t("fasil.autumn"),
            season: "autumn",
        },
        {
            id: 12,
            img: "/IMG/KushImg2.jpg",
            text: t("dataAutumn.text2"),
            fasil: t("fasil.autumn"),
            season: "autumn",
        },
        {
            id: 13,
            img: "/IMG/KushImg3.jpg",
            text: t("dataAutumn.text3"),
            fasil: t("fasil.autumn"),
            season: "autumn",
        },
        {
            id: 14,
            img: "/IMG/KushImg4.jpg",
            text: t("dataAutumn.text4"),
            fasil: t("fasil.autumn"),
            season: "autumn",
        },
        {
            id: 15,
            img: "/IMG/KushImg5.jpg",
            text: t("dataAutumn.text5"),
            fasil: t("fasil.autumn"),
            season: "autumn",
        },
        {
            id: 16,
            img: "/IMG/KushImg6.jpg",
            text: t("dataAutumn.text6"),
            fasil: t("fasil.autumn"),
            season: "autumn",
        },
        {
            id: 17,
            img: "/IMG/KushImg7.jpg",
            text: t("dataAutumn.text7"),
            fasil: t("fasil.autumn"),
            season: "autumn",
        },
        {
            id: 18,
            img: "/IMG/KushImg8.jpg",
            text: t("dataAutumn.text8"),
            fasil: t("fasil.autumn"),
            season: "autumn",
        },
        {
            id: 19,
            img: "/IMG/KushImg9.jpg",
            text: t("dataAutumn.text9"),
            fasil: t("fasil.autumn"),
            season: "autumn",
        },
        {
            id: 20,
            img: "/IMG/KushImg10.jpg",
            text: t("dataAutumn.text10"),
            fasil: t("fasil.autumn"),
            season: "autumn",
        },
        {
            id: 21,
            img: "/IMG/YozImg.jpg",
            text: t("dataSummer.text"),
            fasil: t("fasil.summer"),
            season: "summer",
        },
        {
            id: 22,
            img: "/IMG/YozImg2.jpg",
            text: t("dataSummer.text2"),
            fasil: t("fasil.summer"),
            season: "summer",
        },
        {
            id: 23,
            img: "/IMG/YozImg3.jpg",
            text: t("dataSummer.text3"),
            fasil: t("fasil.summer"),
            season: "summer",
        },
        {
            id: 24,
            img: "/IMG/YozImg4.jpg",
            text: t("dataSummer.text4"),
            fasil: t("fasil.summer"),
            season: "summer",
        },
        {
            id: 25,
            img: "/IMG/YozImg5.jpg",
            text: t("dataSummer.text5"),
            fasil: t("fasil.summer"),
            season: "summer",
        },
        {
            id: 26,
            img: "/IMG/YozImg6.jpg",
            text: t("dataSummer.text6"),
            fasil: t("fasil.summer"),
            season: "summer",
        },
        {
            id: 27,
            img: "/IMG/YozImg7.jpg",
            text: t("dataSummer.text7"),
            fasil: t("fasil.summer"),
            season: "summer",
        },
        {
            id: 28,
            img: "/IMG/YozImg8.jpg",
            text: t("dataSummer.text8"),
            fasil: t("fasil.summer"),
            season: "summer",
        },
        {
            id: 29,
            img: "/IMG/YozImg9.jpg",
            text: t("dataSummer.text9"),
            fasil: t("fasil.summer"),
            season: "summer",
        },
        {
            id: 30,
            img: "/IMG/YozImg10.jpg",
            text: t("dataSummer.text10"),
            fasil: t("fasil.summer"),
            season: "summer",
        },
    ];
};

export default useAllItems;

